[project]
name = "uniinfo-editor"
version = "1.0.0a1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prompt-toolkit>=3.0.51",
]
[project.scripts]
uniinfo_editor = "uniinfo_editor:run"